In [1]:
##1Create Two numpy array of size 4 X 5 and 5 X 4.
import numpy as np
import random as rand

In [2]:
arra1=np.array(np.arange(0,20).reshape(5,4))
arra2=np.array(np.arange(0,20).reshape(4,5))

In [3]:
arra1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
arra2


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
#2.Randomly Initalize that array
array=np.random.randint(1, 100, size=(4, 5))


In [6]:
array

array([[82, 99, 46, 90,  9],
       [16, 62, 29, 57, 17],
       [95, 31, 12,  6, 48],
       [ 3, 39, 74, 43, 18]])

In [7]:
#3.Perform matrix multiplication

In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.dot(x, y))

[[19 22]
 [43 50]]


In [9]:
print(np.dot(arra1,arra2))

[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]
 [430 484 538 592 646]
 [550 620 690 760 830]]


In [10]:
#4.4) Perform elementwise matrix multiplication

In [11]:
print(np.multiply(arra1,arra1))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


In [12]:
#5.Find mean, median of the first matrix.

In [13]:
np.mean(arra1)

9.5

In [14]:
arra1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
np.mean(arra1,axis=0)

array([ 8.,  9., 10., 11.])

In [16]:
np.mean(arra1,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [17]:
np.median(arra1)

9.5

In [18]:
np.median(arra1,axis=0)

array([ 8.,  9., 10., 11.])

In [19]:
np.median(arra1,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [20]:
#6.Get the transpose of that Matrix that you created. Create a square matrix and find its deter-
#minant.

In [21]:
print(arra1.T)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [22]:
# square matrix 3*3

In [23]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.linalg.det(array3)

0.0

In [26]:
#Obtain each row in the second column of the first array.


In [27]:
array3[:,1]

array([2, 5, 8])

In [28]:
#8.Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version


In [29]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

In [ ]:
data=pd.read_csv('/content/mtcars.csv',usecols=['mpg',	'cyl',	'disp'	,'hp'	,'drat',	'wt'	,'qsec'	,'vs','am','gear','carb'])

In [ ]:
array1=np.array(data)


In [ ]:
array1

In [ ]:
nparrayCentered = array1.T - np.mean(array1, axis=1) # Remove the mean for␣
##,→each row
nparrayCentered = nparrayCentered.T #

In [ ]:
nparrayCentered