In [ ]:
import numpy as np
import io
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer.csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

# Declare label as last column in the source file

In [ ]:
#Declaring X as all columns excluding last
X = data.iloc[:,:-1].values

#Declare label as last column in the source file
Y = data.iloc[:,-1].values


In [ ]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X,Y ,
                                   random_state=36, 
                                   test_size=0.25, 
                                   shuffle=True)

In [ ]:
from os import XATTR_SIZE_MAX
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.95591499, -1.03853963],
       [ 0.76240994, -0.28464395],
       [ 0.47215235,  1.86105915],
       [-0.78563054,  0.52724371],
       [ 1.92344029,  0.93318754],
       [-0.30186789, -1.32849951],
       [ 1.53643017,  1.02017551],
       [ 2.11694535, -1.00954364],
       [-0.20511536,  0.17929186],
       [ 0.37539982, -0.42962389],
       [ 0.85916247, -1.1255276 ],
       [-0.30186789,  0.81720359],
       [-1.07588813, -0.31363994],
       [-0.9791356 ,  0.29527581],
       [-1.17264066,  1.42611934],
       [ 0.76240994, -1.3574955 ],
       [ 0.18189476,  0.17929186],
       [ 0.18189476,  2.12202305],
       [-0.88238307, -0.74857975],
       [-1.17264066,  0.49824772],
       [ 1.82668776, -1.03853963],
       [ 1.43967764,  0.38226377],
       [-0.78563054,  1.91905113],
       [ 0.08514223,  0.23728383],
       [-0.0116103 , -0.28464395],
       [-0.49537295, -0.80657173],
       [-1.17264066, -0.98054766],
       [-0.49537295, -0.25564796],
       [ 0.85916247,

In [ ]:
X_test

array([[-1.23439718, -0.20022908],
       [ 1.93072379, -0.38448897],
       [-0.76893821, -0.41519895],
       [-0.48966283, -0.20022908],
       [-0.86203001,  0.72107037],
       [-1.14130539, -1.24436846],
       [ 2.20999917, -0.93726864],
       [-1.69985615,  0.29113063],
       [ 1.65144841, -1.42862835],
       [-0.11729566, -0.78371873],
       [-1.32748897, -0.29235903],
       [ 0.06888793,  1.98017962],
       [ 1.09289765, -1.3364984 ],
       [ 0.25507151,  1.88804967],
       [-0.21038745, -0.90655866],
       [-0.11729566,  0.07616075],
       [-1.14130539, -0.53803888],
       [-0.02420387, -0.29235903],
       [ 2.11690738,  1.76520975],
       [-0.02420387, -0.69158879],
       [-1.60676435,  0.38326057],
       [-0.11729566, -0.59945884],
       [ 0.34816331, -0.47661892],
       [-0.11729566, -1.06010857],
       [-1.04821359,  0.19900068],
       [ 0.90671407,  0.29113063],
       [-1.04821359, -1.21365848],
       [-1.14130539,  0.5061005 ],
       [ 0.4412551 ,

In [ ]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [ ]:
entries = len(X_train[:,0])


In [ ]:
entries

300

In [ ]:
for weights in range(len_x):
  w.append(0)

In [ ]:
w

[0, 0]

In [ ]:
def sigmoid(z):
  return (1/(1+np.exp(-z)))


In [ ]:
def predict(inputs):
  z=np.dot(inputs,w)+b
  h=sigmoid(z)
  for i in range((len(h))):
    if(h[i]>=0.5):
      h[i]=1
    else:
      h[i]=0
  return h
  


In [ ]:
from scipy.optimize.minpack import shape
def loss_func(y,y1):
  total_loss=np.sum(-y*np.log(y1)-(1-y)*np.log(1-y1))
  m=y.shape[0]
  j=total_loss/m
  return j

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)

In [ ]:
for i in range(3000):
    z = np.dot(X_train, w) + b
    y_pred = sigmoid(z)
    l = loss_func(y_train, y_pred)
    dw = np.dot((y_pred-y_train).T, X_train)/X_train.shape[0]
    db = np.mean(y_pred-y_train)
    w = w - alpha * dw
    b = b - alpha* db
    print("Round:",i,"Weight:",w,"Bias:",b,"loss:",l)

Round: 0 Weight: [0.02958692 0.01668477] Bias: 0.1800166002687522 loss: 0.728138869381592
Round: 1 Weight: [0.05837634 0.03284235] Bias: 0.16052977733672263 loss: 0.7128192882175102
Round: 2 Weight: [0.08638905 0.04848866] Bias: 0.14153035705536682 loss: 0.698323504164618
Round: 3 Weight: [0.11364679 0.06364015] Bias: 0.12300830699723174 loss: 0.6846083559276838
Round: 4 Weight: [0.14017197 0.07831362] Bias: 0.10495289345763967 loss: 0.6716315049965728
Round: 5 Weight: [0.16598743 0.09252607] Bias: 0.08735283009614313 loss: 0.6593517304230658
Round: 6 Weight: [0.19111621 0.10629448] Bias: 0.07019641580208034 loss: 0.6477291629566146
Round: 7 Weight: [0.21558138 0.11963578] Bias: 0.05347166021270745 loss: 0.6367254628621289
Round: 8 Weight: [0.23940589 0.13256665] Bias: 0.03716639604690687 loss: 0.6263039469490861
Round: 9 Weight: [0.2626124  0.14510349] Bias: 0.021268378024426757 loss: 0.6164296710003092
Round: 10 Weight: [0.28522318 0.15726231] Bias: 0.005765368616752357 loss: 0.60706

In [ ]:
X_train


array([[ 0.95591499, -1.03853963],
       [ 0.76240994, -0.28464395],
       [ 0.47215235,  1.86105915],
       [-0.78563054,  0.52724371],
       [ 1.92344029,  0.93318754],
       [-0.30186789, -1.32849951],
       [ 1.53643017,  1.02017551],
       [ 2.11694535, -1.00954364],
       [-0.20511536,  0.17929186],
       [ 0.37539982, -0.42962389],
       [ 0.85916247, -1.1255276 ],
       [-0.30186789,  0.81720359],
       [-1.07588813, -0.31363994],
       [-0.9791356 ,  0.29527581],
       [-1.17264066,  1.42611934],
       [ 0.76240994, -1.3574955 ],
       [ 0.18189476,  0.17929186],
       [ 0.18189476,  2.12202305],
       [-0.88238307, -0.74857975],
       [-1.17264066,  0.49824772],
       [ 1.82668776, -1.03853963],
       [ 1.43967764,  0.38226377],
       [-0.78563054,  1.91905113],
       [ 0.08514223,  0.23728383],
       [-0.0116103 , -0.28464395],
       [-0.49537295, -0.80657173],
       [-1.17264066, -0.98054766],
       [-0.49537295, -0.25564796],
       [ 0.85916247,

In [ ]:
y_pred=predict(X_test)

In [ ]:
y_pred

array([0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#print actual and predicted values in a table
print("actual Value\tpredicted values")
for i in range(len(y_test)):
    print(y_test[i],"\t\t",int(y_pred[i]))

actual Value	predicted values
0 		 0
1 		 1
0 		 0
0 		 0
1 		 0
0 		 0
1 		 1
0 		 0
1 		 1
0 		 0
0 		 0
1 		 1
1 		 0
1 		 1
0 		 0
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 1
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 1
0 		 1
0 		 0
0 		 0
0 		 0
1 		 0
1 		 1
0 		 0
1 		 1
0 		 0
1 		 0
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 0
0 		 0
1 		 0
0 		 0
1 		 1
1 		 1
1 		 1
1 		 1
0 		 0
0 		 0
1 		 1
1 		 1
0 		 0
1 		 1
0 		 0
1 		 1
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
0 		 0
1 		 0
1 		 1
0 		 0
0 		 1
0 		 1
0 		 0
1 		 1
0 		 0
1 		 1
1 		 0
1 		 1
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0


In [ ]:
x=0
for i in range(len(y_test)):
  if(y_test[i]==y_pred[i]):
    x+=1
print((x/len(y_test))*100)


86.0


In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
from sklearn.metrics import  accuracy_score
from sklearn.metrics import  precision_score
from sklearn.metrics import  recall_score

#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_test_pred = LR.predict(X_test)
accuracy = accuracy_score(y_test, y_test_pred)*100
print("Accuracy: ", accuracy,"%")

Accuracy:  86.0 %


In [ ]:
y_pred1=predict(X)

In [ ]:
print("actual Value\tpredicted values")
for i in range(len(Y)):
    print(Y[i],"\t\t",int(y_pred1[i]))

In [ ]:
precision = precision_score(y_test, y_test_pred)*100
print("Precision: ", precision,"%")

Precision:  87.5 %


In [ ]:
recall = recall_score(y_test, y_test_pred)*100
print("Recall: ", recall,"%")

Recall:  73.68421052631578 %
