In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')

In [3]:
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')

In [4]:
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [5]:
 # Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)

tensor([[0.9371, 0.1617, 1.7898]], requires_grad=True)
tensor([1.1184], requires_grad=True)


In [6]:
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b

In [7]:
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[157.3220],
        [215.1714],
        [208.1202],
        [169.8797],
        [206.5870]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [8]:
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)

Loss : tensor([13761.8389], grad_fn=<DivBackward0>)


In [9]:
# Compute gradients
print("Gradient :",output.backward())

Gradient : None


In [10]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[0.9371, 0.1617, 1.7898]], requires_grad=True)
tensor([[19836.3184, 18736.3789, 12334.1719]])


In [11]:
# Gradients for bias
print(b)
print(b.grad)

tensor([1.1184], requires_grad=True)
tensor([230.4321])


In [12]:
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)

tensor([[ 0.7388, -0.0257,  1.6665]], requires_grad=True)
tensor([1.1161], requires_grad=True)


In [13]:
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)

New Loss : tensor([6395.3364], grad_fn=<DivBackward0>)


In [14]:
# Train for 100 epochs
for i in range(200):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [15]:
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([48.7851], grad_fn=<DivBackward0>)


Pytorch_Built_Ins

In [16]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [17]:
def model1(x):
  return x @ w.t() +b

In [18]:
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[ 57.6498],
        [ 87.2404],
        [106.4697],
        [ 23.2996],
        [109.6002]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [19]:
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)

Loss : tensor(48.7851, grad_fn=<MseLossBackward0>)


In [20]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.4723,  0.5428,  1.2712]], requires_grad=True)
tensor([[  74.4594, -131.9480,  101.4671]])
tensor([1.1040], requires_grad=True)
tensor([1.3039])


In [21]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [22]:
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)

tensor([29.4179], grad_fn=<DivBackward0>)
